[package]
name = "sleigh-6502"
version = "0.1.0"
edition = "2021"
publish = false

[build-dependencies]
sleigh-build-script-helper = { path = "../../build-script-helper" }

[dev-dependencies]
disasm6502 = "0.2.2"
