[package]
name = "sleigh-generator"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
sleigh-types = { path = "../types" }
heck = "0.4.1"
proc-macro2 = "1.0.93"
quote = "1.0.38"
syn = "1.0.109"
