[package]
name = "sleigh-generator"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
sleigh-parser = { path = "../sleigh-parser" }
heck = "0.4.0"
proc-macro2 = "1.0.49"
quote = "1.0.23"
